
main: main.o class.o funkcje.o
	g++ main.o class.o funkcje.o -o program
main.o : main.cpp
	g++ -c main.cpp
class.o : class.cpp
	g++ -c class.cpp
fun1.o : fun1.cpp
	g++ -c funkcje.cpp
fun2.o : fun2.cpp
	g++ -c fun2.cpp

